// Code generated by "stringer -type=Type"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Hiragana-0]
	_ = x[Katakana-1]
	_ = x[Kanji-2]
	_ = x[Okurigana-3]
	_ = x[Q-4]
}

const _Type_name = "HiraganaKatakanaKanjiOkuriganaQ"

var _Type_index = [...]uint8{0, 8, 16, 21, 30, 31}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
